############################################################
# Dockerfile to build TJCodeIDE Containers
# # Based on Ubuntu
# ############################################################

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER nikefd <nikefd@gmail.com>

# Updata the sources list
RUN apt-get update

# Install some tools
RUN apt-get install g++-4.8
